### ISSUE TITLE
import error, I already cd ops & sh make.sh # compile deformable attention

### ISSUE THREAD

**Issue by nakuda1** [czczup/ViT-Adapter#101]
Sorry to bother you. I already cd ops & sh make.sh # compile deformable attention in segmentation part
When I run train.py in the segementation part, it has an error. 
Can you help me to solve it?
 ----------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import mmseg_custom   # noqa: F401,F403
  File "/root/ViT-Adapter/segmentation/mmseg_custom/__init__.py", line 3, in <module>
    from .models import *  # noqa: F401,F403
  File "/root/ViT-Adapter/segmentation/mmseg_custom/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/root/ViT-Adapter/segmentation/mmseg_custom/models/backbones/__init__.py", line 2, in <module>
    from .beit_adapter import BEiTAdapter
  File "/root/ViT-Adapter/segmentation/mmseg_custom/models/backbones/beit_adapter.py", line 16, in <module>
    from .adapter_modules import SpatialPriorModule, deform_inputs
  File "/root/ViT-Adapter/segmentation/mmseg_custom/models/backbones/adapter_modules.py", line 8, in <module>
    from ops.modules import MSDeformAttn
ModuleNotFoundError: No module named 'ops.modules'

![image](https://github.com/czczup/ViT-Adapter/assets/122974900/db9ca56a-5b60-4e25-80a2-25167e20b9a1)

**Comment by windygoo** [comment]
have you solved it? I meet the same issue.

**Comment by duanduanduanyuchen** [comment]
Hi, maybe you can try to run the command:
`export PYTHONPATH=\your\path\to\dir`
replace `\your\path\to\dir` by your path to the segmentation dir and run the code again.

**Comment by czczup** [comment]
If you meet dist_train.sh: Bad substitution when using cmd `sh dist_train.sh`, you can try `bash dist_train.sh`.

**Comment by CX1888** [comment]
Met the same issue, how to resolve it?
