### ISSUE TITLE
undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm

### ISSUE THREAD

**Issue by yansenhan** [czczup/ViT-Adapter#135]
```
Traceback (most recent call last):
  File "train.py", line 11, in &lt;module&gt;
    import mmseg_custom   # noqa: F401,F403
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/mmseg_custom/__init__.py", line 3, in &lt;module&gt;
    from .models import *  # noqa: F401,F403
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/mmseg_custom/models/__init__.py", line 2, in &lt;module&gt;
    from .backbones import *  # noqa: F401,F403
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/mmseg_custom/models/backbones/__init__.py", line 2, in &lt;module&gt;
    from .beit_adapter import BEiTAdapter
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/mmseg_custom/models/backbones/beit_adapter.py", line 10, in &lt;module&gt;
    from ops.modules import MSDeformAttn
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/ops/modules/__init__.py", line 9, in &lt;module&gt;
    from .ms_deform_attn import MSDeformAttn
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/ops/modules/ms_deform_attn.py", line 19, in &lt;module&gt;
    from ..functions import MSDeformAttnFunction
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/ops/functions/__init__.py", line 9, in &lt;module&gt;
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/yansen/hanyansen/ViT-Adapter/segmentation/ops/functions/ms_deform_attn_func.py", line 11, in &lt;module&gt;
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/yansen/mambaforge-pypy3/envs/vit-adapter/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm
```

Anyone can help with this problem.
I followed the official instruction (my python is 3.8):
```
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
pip install timm==0.4.12
pip install mmdet==2.22.0
pip install instaboostfast # for htc++
cd ops & sh make.sh # compile deformable attention
```
the cmd is:
```
python train.py configs/ade20k/upernet_beit_adapter_large_640_160k_ade20k_ss.py
```
After running the cmd, I got the error above

**Comment by czczup** [comment]
I guess the CUDA version shown by using cmd `nvcc -V` is different with the CUDA version of pytorch.

**Comment by yansenhan** [comment]
> I guess the CUDA version shown by using cmd `nvcc -V` is different with the CUDA version of pytorch.

Thanks for the advice. After changing to the suitable cuda version, I use mmcv==1.4.8, and now can smoothly run the code.
