### ISSUE TITLE
Download Pretrained Model, Finetune on separate dataset

### ISSUE THREAD

**Issue by dhosk22** [czczup/ViT-Adapter#58]
Hi, for a project in my deep learning course, I am attempting to download your pretrained model for semantic segmentation tested on cityscapes dataset. I want to finetune it on a separate dataset that I found on the web. I am having quite a difficult time getting my [colab notebook](https://colab.research.google.com/drive/1S7jspVAX68jgFGdDqTQ7Ww8T8dlZGdjz#scrollTo=e7lyW0Uh_Gsh) set up. I'm hoping I could get some advice in order to move forward with this project.

**Comment by czczup** [comment]
Hi, this is an [example](https://colab.research.google.com/drive/1L0Gq4qhPoGMVmJklX82vIu-mMBIvphDz?usp=sharing) of colab notebook, provided by [dudifrid](https://github.com/dudifrid).

**Comment by dhosk22** [comment]
Thanks for the quick response. Is the purpose of the checkpoint to save on computation? Also, why is the check using a Cocostuff model, while the model used for testing is the Ade20k?

**Comment by czczup** [comment]
> Thanks for the quick response. Is the purpose of the checkpoint to save on computation? Also, why is the check using a Cocostuff model, while the model used for testing is the Ade20k?

`with_cp=True` is used to save GPU memory. Besides, there might be some mistakes in this example. You should use a ade20k model for the testing of ade20k dataset.

**Comment by IamShubhamGupto** [comment]
Hey @czczup 
cc: @dudifrid

I tried the [example](https://colab.research.google.com/drive/1L0Gq4qhPoGMVmJklX82vIu-mMBIvphDz?usp=sharing) you linked here and it gave the following error stack trace - 
```
Traceback (most recent call last):
  File "image_demo.py", line 7, in <module>
    import mmseg_custom   # noqa: F401,F403
  File "/content/ViT-Adapter/segmentation/mmseg_custom/__init__.py", line 3, in <module>
    from .models import *  # noqa: F401,F403
  File "/content/ViT-Adapter/segmentation/mmseg_custom/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/content/ViT-Adapter/segmentation/mmseg_custom/models/backbones/__init__.py", line 2, in <module>
    from .beit_adapter import BEiTAdapter
  File "/content/ViT-Adapter/segmentation/mmseg_custom/models/backbones/beit_adapter.py", line 9, in <module>
    from mmseg.models.builder import BACKBONES
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/backbones/__init__.py", line 6, in <module>
    from .fast_scnn import FastSCNN
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.8/dist-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops7resize_4callERKNS_6TensorEN3c108ArrayRefIlEENS5_8optionalINS5_12MemoryFormatEEE
```

Any recommendations?
