### ISSUE TITLE
CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by jisu9867** [czczup/ViT-Adapter#66]
Hi. i have a trouble with my local window system doing these code

ln -s ../detection/ops ./
cd ops & sh make.sh # compile deformable attention

here is my error message

  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'MultiScaleDeformableAttention' extension
Emitting ninja build file D:\GitHub\ViT-Adapter\segmentation\ops\build\temp.win-amd64-cpython-39\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -ID:\GitHub\ViT-Adapter\segmentation\ops\src -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\TH -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" -c D:\GitHub\ViT-Adapter\segmentation\ops\src\cpu\ms_deform_attn_cpu.cpp /FoD:\GitHub\ViT-Adapter\segmentation\ops\build\temp.win-amd64-cpython-39\Release\GitHub\ViT-Adapter\segmentation\ops\src\cpu\ms_deform_attn_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/GitHub/ViT-Adapter/segmentation/ops/build/temp.win-amd64-cpython-39/Release/GitHub/ViT-Adapter/segmentation/ops/src/cpu/ms_deform_attn_cpu.obj
cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -ID:\GitHub\ViT-Adapter\segmentation\ops\src -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\TH -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" -c D:\GitHub\ViT-Adapter\segmentation\ops\src\cpu\ms_deform_attn_cpu.cpp /FoD:\GitHub\ViT-Adapter\segmentation\ops\build\temp.win-amd64-cpython-39\Release\GitHub\ViT-Adapter\segmentation\ops\src\cpu\ms_deform_attn_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[2/3] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -ID:\GitHub\ViT-Adapter\segmentation\ops\src -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\TH -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" -c D:\GitHub\ViT-Adapter\segmentation\ops\src\vision.cpp /FoD:\GitHub\ViT-Adapter\segmentation\ops\build\temp.win-amd64-cpython-39\Release\GitHub\ViT-Adapter\segmentation\ops\src\vision.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/GitHub/ViT-Adapter/segmentation/ops/build/temp.win-amd64-cpython-39/Release/GitHub/ViT-Adapter/segmentation/ops/src/vision.obj
cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -ID:\GitHub\ViT-Adapter\segmentation\ops\src -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\TH -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\include -IC:\Users\jslee\CONDA~1\envs\VIT-AD~1\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\inninja: fatal: ReadFile: ?몃뱾???섎せ?섏뿀?듬땲??

clude\10.0.22000.0\\cppwinrt" -c D:\GitHub\ViT-Adapter\segmentation\ops\src\vision.cpp /FoD:\GitHub\ViT-Adapter\segmentation\ops\build\temp.win-amd64-cpython-39\Release\GitHub\ViT-Adapter\segmentation\ops\src\vision.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GitHub\ViT-Adapter\segmentation\ops\setup.py", line 59, in <module>
    setup(
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\jslee\CONDA~1\envs\VIT-AD~1\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

can you help me? please
is a bad idea to deal with these codes in my window system?

**Comment by woxihuanjiangguo** [comment]
Hello, have you solved this problem?
